### PR TITLE
Liberally handle unknown elements

### PR DESCRIPTION
**Pull request by smparkes**
As it stands, hpricot is very conservative about element content models. It assumes the content model of any unknown element is text only and unknown elements are not allowed in most known elements.

This is particularly problematic with html5: hpricot doesn't know the new html5 tag set.

In theory, hpricot could be taught the html5 spec (though it's a moving target ...) But that wouldn't change the fact that hpricot isn't really following what browsers do (liberally ignore unknown tags) and doesn't seem like it fits the spirit of hpricot's goal of being a good html cleaner-upper.

So this patch simply makes the content model of unknown elements anything and allows any element to contain unknown elements. I think this matches what browsers do.

### CODE REVIEW

**Comment by smparkes** [comment]
For what it's worth, the diff is very small. If you do a git diff -w it's a lot cleaner; adding a conditional caused some reindenting.

**Comment by evanphx** [comment]
While I understand your need for something liked his, hpricot is really in maintenance only mode at this point. There are no plans for new features or feature releases, which I'd think your code counts as.

Have you considered moving to nokogiri instead? Do you have a heavy usage of hpricot that demands this new functionality?

As on of the maintenance maintainers, I'm not keen to do new work on hpricot for fear of it requiring more of my time.

**Comment by smparkes** [comment]
I don't use hpricot (directly) either.

The impetus for this is haml: there are open bugs for html2haml's handling of html5 and haml uses hpricot. The first thing I looked at was using nokogiri in haml but wholesale replacing hpricot with nokogiri is going to be a big task. Conversely, it's a very small patch to hpricot.

**Comment by smparkes** [comment]
https://github.com/nex3/haml/issues/479

**Comment by evanphx** [comment]
Given your justification for the change, seems reasonable to go ahead and merge it and release a new release. It does feel more like a bug fix than a feature. @nicksieger do you have any problems with me merging this and doing a new release?

**Comment by nicksieger** [comment]
Nope, not at all. @evanphx do you have all the cross-compile stuff set up? Let me know, I can run a quick build and push the gems if everything is all tagged and ready to go.

**Comment by smparkes** [comment]
Thanks!

**Comment by evanphx** [comment]
@nicksieger I don't have it setup on this machine, no. If you've got everything setup, would you mind bumping a release?

**Pull request merged**
