### PR TITLE
children of an unknown tag incorrectly added to tag's parent

### PR DESCRIPTION
**Pull request by smparkes**
See https://github.com/hpricot/hpricot/issues/48

### CODE REVIEW

**Comment by smparkes** [comment]
Whoops. Left a pp in there.

And I may have another related case that's (still) failing ...

**Comment by nicksieger** [comment]
Is this separate from your comment on #25?

**Comment by smparkes** [comment]
Yup, unrelated. I just happened to notice #25 while working on this.

As far as this pull request goes, I found another failure that I'm working on so I'll close this request and resubmit when I have a fix for that case, too.

**Comment by smparkes** [comment]
Replaced by https://github.com/hpricot/hpricot/pull/60.

**Pull request closed without merging**
